[package]
name = "my-dns-resolver"
version = "0.1.0"
edition = "2021"

[lib]
name = "nss_mydns"
crate-type = ["cdylib"]     # NSS module must be a C shared library

[[bin]]
name = "mydns-daemon"
path = "src/daemon.rs"

[dependencies]
libnss = "0.8"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libc = "0.2"
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "2"
toml = "0.8"
cel-interpreter = { version = "0.10", features = ["regex"] }
